name: darkness_dungeon
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.18.1
  flame_splash_screen: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/joystick_background.png
    - assets/images/joystick_knob.png
    - assets/images/joystick_atack.png
    - assets/images/knight_idle.png
    - assets/images/knight_idle_left.png
    - assets/images/knight_run.png
    - assets/images/knight_run_left.png
    - assets/images/tile/floor_1.png
    - assets/images/tile/floor_2.png
    - assets/images/tile/floor_3.png
    - assets/images/tile/floor_4.png
    - assets/images/tile/floor_5.png
    - assets/images/tile/floor_6.png
    - assets/images/tile/floor_7.png
    - assets/images/tile/floor_8.png
    - assets/images/tile/floor_9.png
    - assets/images/tile/floor_10.png
    - assets/images/tile/wall.png
    - assets/images/tile/wall_bottom.png
    - assets/images/tile/wall_top.png
    - assets/images/tile/wall_left.png
    - assets/images/tile/wall_right.png
    - assets/images/tile/wall_top_inner_left.png
    - assets/images/tile/wall_top_inner_right.png
    - assets/images/tile/wall_bottom_right.png
    - assets/images/tile/wall_left_and_top.png
    - assets/images/tile/wall_right_and_bottom.png
    - assets/images/tile/wall_bottom_left.png
    - assets/images/tile/wall_left_and_bottom.png
    - assets/images/tile/wall_turn_left_top.png
    - assets/images/tile/empty.png
    - assets/images/slime_idle.png
    - assets/images/slime_run_right.png
    - assets/images/goblin_idle.png
    - assets/images/goblin_run_right.png
    - assets/images/itens/barrel.png
    - assets/images/itens/bookshelf.png
    - assets/images/itens/flag_red.png
    - assets/images/itens/flag_green.png
    - assets/images/itens/prisoner.png
    - assets/images/itens/table.png
    - assets/images/itens/chest_spritesheet.png
    - assets/images/itens/torch_spritesheet.png
    - assets/images/health_ui.png
    - assets/images/crypt.png
    - assets/images/atack_effect_right.png
    - assets/images/atack_effect_left.png
    - assets/images/atack_effect_bottom.png
    - assets/images/atack_effect_top.png
    - assets/images/enemy_explosin.png
    - assets/images/boss_idle.png
    - assets/images/boos_run_right.png
    - assets/images/boos_run_left.png
    - assets/images/mini_boss_idle.png
    - assets/images/mini_boss_run_left.png
    - assets/images/mini_boss_run_right.png
    - assets/game_over.png
    - assets/play_again.png
    - assets/logo_flame.png
    - assets/images/enemy/
    - assets/images/player/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Normal
     fonts:
       - asset: fonts/Minecraft.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
